//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.01 at 11:16:39 PM BST 
//


package org.lolobored.plex.infrastructure;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="access_token" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="library_section" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="key" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="device" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="token" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="owned" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                 &lt;attribute name="username" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="title" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="thumb" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="allow_sync" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                 &lt;attribute name="allow_camera_upload" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                 &lt;attribute name="allow_channels" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                 &lt;attribute name="allow_tuners" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                 &lt;attribute name="filter_all" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="filter_movies" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="filter_music" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="filter_photos" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="filter_television" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="scrobble_types" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "accessToken"
})
@XmlRootElement(name = "access_tokens")
public class AccessTokens {

    @XmlElement(name = "access_token")
    protected List<AccessTokens.AccessToken> accessToken;

    /**
     * Gets the value of the accessToken property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the accessToken property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAccessToken().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AccessTokens.AccessToken }
     * 
     * 
     */
    public List<AccessTokens.AccessToken> getAccessToken() {
        if (accessToken == null) {
            accessToken = new ArrayList<AccessTokens.AccessToken>();
        }
        return this.accessToken;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="library_section" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="key" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="device" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="token" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="owned" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *       &lt;attribute name="username" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="title" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="thumb" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="allow_sync" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *       &lt;attribute name="allow_camera_upload" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *       &lt;attribute name="allow_channels" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *       &lt;attribute name="allow_tuners" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *       &lt;attribute name="filter_all" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="filter_movies" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="filter_music" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="filter_photos" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="filter_television" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="scrobble_types" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "content"
    })
    public static class AccessToken {

        @XmlElementRef(name = "library_section", type = JAXBElement.class, required = false)
        @XmlMixed
        protected List<Serializable> content;
        @XmlAttribute(name = "device")
        protected String device;
        @XmlAttribute(name = "token")
        protected String token;
        @XmlAttribute(name = "owned")
        protected Byte owned;
        @XmlAttribute(name = "username")
        protected String username;
        @XmlAttribute(name = "title")
        protected String title;
        @XmlAttribute(name = "id")
        protected Integer id;
        @XmlAttribute(name = "thumb")
        protected String thumb;
        @XmlAttribute(name = "allow_sync")
        protected Byte allowSync;
        @XmlAttribute(name = "allow_camera_upload")
        protected Byte allowCameraUpload;
        @XmlAttribute(name = "allow_channels")
        protected Byte allowChannels;
        @XmlAttribute(name = "allow_tuners")
        protected Byte allowTuners;
        @XmlAttribute(name = "filter_all")
        protected String filterAll;
        @XmlAttribute(name = "filter_movies")
        protected String filterMovies;
        @XmlAttribute(name = "filter_music")
        protected String filterMusic;
        @XmlAttribute(name = "filter_photos")
        protected String filterPhotos;
        @XmlAttribute(name = "filter_television")
        protected String filterTelevision;
        @XmlAttribute(name = "scrobble_types")
        protected String scrobbleTypes;

        /**
         * Gets the value of the content property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the content property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getContent().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * {@link JAXBElement }{@code <}{@link AccessTokens.AccessToken.LibrarySection }{@code >}
         * 
         * 
         */
        public List<Serializable> getContent() {
            if (content == null) {
                content = new ArrayList<Serializable>();
            }
            return this.content;
        }

        /**
         * Gets the value of the device property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDevice() {
            return device;
        }

        /**
         * Sets the value of the device property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDevice(String value) {
            this.device = value;
        }

        /**
         * Gets the value of the token property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getToken() {
            return token;
        }

        /**
         * Sets the value of the token property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setToken(String value) {
            this.token = value;
        }

        /**
         * Gets the value of the owned property.
         * 
         * @return
         *     possible object is
         *     {@link Byte }
         *     
         */
        public Byte getOwned() {
            return owned;
        }

        /**
         * Sets the value of the owned property.
         * 
         * @param value
         *     allowed object is
         *     {@link Byte }
         *     
         */
        public void setOwned(Byte value) {
            this.owned = value;
        }

        /**
         * Gets the value of the username property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUsername() {
            return username;
        }

        /**
         * Sets the value of the username property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUsername(String value) {
            this.username = value;
        }

        /**
         * Gets the value of the title property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTitle() {
            return title;
        }

        /**
         * Sets the value of the title property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTitle(String value) {
            this.title = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setId(Integer value) {
            this.id = value;
        }

        /**
         * Gets the value of the thumb property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getThumb() {
            return thumb;
        }

        /**
         * Sets the value of the thumb property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setThumb(String value) {
            this.thumb = value;
        }

        /**
         * Gets the value of the allowSync property.
         * 
         * @return
         *     possible object is
         *     {@link Byte }
         *     
         */
        public Byte getAllowSync() {
            return allowSync;
        }

        /**
         * Sets the value of the allowSync property.
         * 
         * @param value
         *     allowed object is
         *     {@link Byte }
         *     
         */
        public void setAllowSync(Byte value) {
            this.allowSync = value;
        }

        /**
         * Gets the value of the allowCameraUpload property.
         * 
         * @return
         *     possible object is
         *     {@link Byte }
         *     
         */
        public Byte getAllowCameraUpload() {
            return allowCameraUpload;
        }

        /**
         * Sets the value of the allowCameraUpload property.
         * 
         * @param value
         *     allowed object is
         *     {@link Byte }
         *     
         */
        public void setAllowCameraUpload(Byte value) {
            this.allowCameraUpload = value;
        }

        /**
         * Gets the value of the allowChannels property.
         * 
         * @return
         *     possible object is
         *     {@link Byte }
         *     
         */
        public Byte getAllowChannels() {
            return allowChannels;
        }

        /**
         * Sets the value of the allowChannels property.
         * 
         * @param value
         *     allowed object is
         *     {@link Byte }
         *     
         */
        public void setAllowChannels(Byte value) {
            this.allowChannels = value;
        }

        /**
         * Gets the value of the allowTuners property.
         * 
         * @return
         *     possible object is
         *     {@link Byte }
         *     
         */
        public Byte getAllowTuners() {
            return allowTuners;
        }

        /**
         * Sets the value of the allowTuners property.
         * 
         * @param value
         *     allowed object is
         *     {@link Byte }
         *     
         */
        public void setAllowTuners(Byte value) {
            this.allowTuners = value;
        }

        /**
         * Gets the value of the filterAll property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFilterAll() {
            return filterAll;
        }

        /**
         * Sets the value of the filterAll property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFilterAll(String value) {
            this.filterAll = value;
        }

        /**
         * Gets the value of the filterMovies property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFilterMovies() {
            return filterMovies;
        }

        /**
         * Sets the value of the filterMovies property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFilterMovies(String value) {
            this.filterMovies = value;
        }

        /**
         * Gets the value of the filterMusic property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFilterMusic() {
            return filterMusic;
        }

        /**
         * Sets the value of the filterMusic property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFilterMusic(String value) {
            this.filterMusic = value;
        }

        /**
         * Gets the value of the filterPhotos property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFilterPhotos() {
            return filterPhotos;
        }

        /**
         * Sets the value of the filterPhotos property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFilterPhotos(String value) {
            this.filterPhotos = value;
        }

        /**
         * Gets the value of the filterTelevision property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFilterTelevision() {
            return filterTelevision;
        }

        /**
         * Sets the value of the filterTelevision property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFilterTelevision(String value) {
            this.filterTelevision = value;
        }

        /**
         * Gets the value of the scrobbleTypes property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getScrobbleTypes() {
            return scrobbleTypes;
        }

        /**
         * Sets the value of the scrobbleTypes property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setScrobbleTypes(String value) {
            this.scrobbleTypes = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="key" type="{http://www.w3.org/2001/XMLSchema}byte" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class LibrarySection {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "key")
            protected Byte key;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the key property.
             * 
             * @return
             *     possible object is
             *     {@link Byte }
             *     
             */
            public Byte getKey() {
                return key;
            }

            /**
             * Sets the value of the key property.
             * 
             * @param value
             *     allowed object is
             *     {@link Byte }
             *     
             */
            public void setKey(Byte value) {
                this.key = value;
            }

        }

    }

}
