//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.01 at 11:16:39 PM BST 
//


package org.lolobored.plex.infrastructure;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Server" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="accessToken" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="address" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="port" type="{http://www.w3.org/2001/XMLSchema}short" />
 *                 &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="scheme" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="host" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="localAddresses" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="machineIdentifier" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="createdAt" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="updatedAt" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="owned" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                 &lt;attribute name="synced" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="friendlyName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="identifier" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="machineIdentifier" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="size" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "server"
})
@XmlRootElement(name = "MediaContainer")
public class MediaContainer {

    @XmlElement(name = "Server")
    protected List<MediaContainer.Server> server;
    @XmlAttribute(name = "friendlyName")
    protected String friendlyName;
    @XmlAttribute(name = "identifier")
    protected String identifier;
    @XmlAttribute(name = "machineIdentifier")
    protected String machineIdentifier;
    @XmlAttribute(name = "size")
    protected Byte size;

    /**
     * Gets the value of the server property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the server property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getServer().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MediaContainer.Server }
     * 
     * 
     */
    public List<MediaContainer.Server> getServer() {
        if (server == null) {
            server = new ArrayList<MediaContainer.Server>();
        }
        return this.server;
    }

    /**
     * Gets the value of the friendlyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFriendlyName() {
        return friendlyName;
    }

    /**
     * Sets the value of the friendlyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFriendlyName(String value) {
        this.friendlyName = value;
    }

    /**
     * Gets the value of the identifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentifier() {
        return identifier;
    }

    /**
     * Sets the value of the identifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentifier(String value) {
        this.identifier = value;
    }

    /**
     * Gets the value of the machineIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMachineIdentifier() {
        return machineIdentifier;
    }

    /**
     * Sets the value of the machineIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMachineIdentifier(String value) {
        this.machineIdentifier = value;
    }

    /**
     * Gets the value of the size property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getSize() {
        return size;
    }

    /**
     * Sets the value of the size property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setSize(Byte value) {
        this.size = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="accessToken" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="address" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="port" type="{http://www.w3.org/2001/XMLSchema}short" />
     *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="scheme" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="host" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="localAddresses" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="machineIdentifier" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="createdAt" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="updatedAt" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="owned" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *       &lt;attribute name="synced" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Server {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "accessToken")
        protected String accessToken;
        @XmlAttribute(name = "name")
        protected String name;
        @XmlAttribute(name = "address")
        protected String address;
        @XmlAttribute(name = "port")
        protected Short port;
        @XmlAttribute(name = "version")
        protected String version;
        @XmlAttribute(name = "scheme")
        protected String scheme;
        @XmlAttribute(name = "host")
        protected String host;
        @XmlAttribute(name = "localAddresses")
        protected String localAddresses;
        @XmlAttribute(name = "machineIdentifier")
        protected String machineIdentifier;
        @XmlAttribute(name = "createdAt")
        protected Integer createdAt;
        @XmlAttribute(name = "updatedAt")
        protected Integer updatedAt;
        @XmlAttribute(name = "owned")
        protected Byte owned;
        @XmlAttribute(name = "synced")
        protected Byte synced;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the accessToken property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAccessToken() {
            return accessToken;
        }

        /**
         * Sets the value of the accessToken property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAccessToken(String value) {
            this.accessToken = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the address property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAddress() {
            return address;
        }

        /**
         * Sets the value of the address property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAddress(String value) {
            this.address = value;
        }

        /**
         * Gets the value of the port property.
         * 
         * @return
         *     possible object is
         *     {@link Short }
         *     
         */
        public Short getPort() {
            return port;
        }

        /**
         * Sets the value of the port property.
         * 
         * @param value
         *     allowed object is
         *     {@link Short }
         *     
         */
        public void setPort(Short value) {
            this.port = value;
        }

        /**
         * Gets the value of the version property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVersion() {
            return version;
        }

        /**
         * Sets the value of the version property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVersion(String value) {
            this.version = value;
        }

        /**
         * Gets the value of the scheme property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getScheme() {
            return scheme;
        }

        /**
         * Sets the value of the scheme property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setScheme(String value) {
            this.scheme = value;
        }

        /**
         * Gets the value of the host property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHost() {
            return host;
        }

        /**
         * Sets the value of the host property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHost(String value) {
            this.host = value;
        }

        /**
         * Gets the value of the localAddresses property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLocalAddresses() {
            return localAddresses;
        }

        /**
         * Sets the value of the localAddresses property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLocalAddresses(String value) {
            this.localAddresses = value;
        }

        /**
         * Gets the value of the machineIdentifier property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMachineIdentifier() {
            return machineIdentifier;
        }

        /**
         * Sets the value of the machineIdentifier property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMachineIdentifier(String value) {
            this.machineIdentifier = value;
        }

        /**
         * Gets the value of the createdAt property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getCreatedAt() {
            return createdAt;
        }

        /**
         * Sets the value of the createdAt property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setCreatedAt(Integer value) {
            this.createdAt = value;
        }

        /**
         * Gets the value of the updatedAt property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getUpdatedAt() {
            return updatedAt;
        }

        /**
         * Sets the value of the updatedAt property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setUpdatedAt(Integer value) {
            this.updatedAt = value;
        }

        /**
         * Gets the value of the owned property.
         * 
         * @return
         *     possible object is
         *     {@link Byte }
         *     
         */
        public Byte getOwned() {
            return owned;
        }

        /**
         * Sets the value of the owned property.
         * 
         * @param value
         *     allowed object is
         *     {@link Byte }
         *     
         */
        public void setOwned(Byte value) {
            this.owned = value;
        }

        /**
         * Gets the value of the synced property.
         * 
         * @return
         *     possible object is
         *     {@link Byte }
         *     
         */
        public Byte getSynced() {
            return synced;
        }

        /**
         * Sets the value of the synced property.
         * 
         * @param value
         *     allowed object is
         *     {@link Byte }
         *     
         */
        public void setSynced(Byte value) {
            this.synced = value;
        }

    }

}
