//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.01 at 11:16:39 PM BST 
//


package org.lolobored.plex.infrastructure;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.lolobored.plex.infrastructure package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AccessTokensAccessTokenLibrarySection_QNAME = new QName("", "library_section");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.lolobored.plex.infrastructure
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AccessTokens }
     * 
     */
    public AccessTokens createAccessTokens() {
        return new AccessTokens();
    }

    /**
     * Create an instance of {@link MediaContainer }
     * 
     */
    public MediaContainer createMediaContainer() {
        return new MediaContainer();
    }

    /**
     * Create an instance of {@link AccessTokens.AccessToken }
     * 
     */
    public AccessTokens.AccessToken createAccessTokensAccessToken() {
        return new AccessTokens.AccessToken();
    }

    /**
     * Create an instance of {@link MediaContainer.Server }
     * 
     */
    public MediaContainer.Server createMediaContainerServer() {
        return new MediaContainer.Server();
    }

    /**
     * Create an instance of {@link AccessTokens.AccessToken.LibrarySection }
     * 
     */
    public AccessTokens.AccessToken.LibrarySection createAccessTokensAccessTokenLibrarySection() {
        return new AccessTokens.AccessToken.LibrarySection();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AccessTokens.AccessToken.LibrarySection }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "library_section", scope = AccessTokens.AccessToken.class)
    public JAXBElement<AccessTokens.AccessToken.LibrarySection> createAccessTokensAccessTokenLibrarySection(AccessTokens.AccessToken.LibrarySection value) {
        return new JAXBElement<AccessTokens.AccessToken.LibrarySection>(_AccessTokensAccessTokenLibrarySection_QNAME, AccessTokens.AccessToken.LibrarySection.class, AccessTokens.AccessToken.class, value);
    }

}
